name: Build-Android

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true   # cần cho KittyMemoryEx

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          local-cache: true

      - name: Build ABIs
        shell: bash
        run: |
          mkdir artifacts
          for abi in armeabi-v7a arm64-v8a x86 x86_64; do
            echo "=========================="
            echo "= Building $abi"
            echo "=========================="
            cmake -S AndKittyInjector -B build/$abi \
              -G Ninja \
              -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
              -DANDROID_ABI=$abi \
              -DANDROID_PLATFORM=android-21 \
              -DCMAKE_CXX_FLAGS="-I${{ github.workspace }}/KittyMemoryEx -I${{ github.workspace }}/KittyMemoryEx/include"
            cmake --build build/$abi --config Release
            mkdir -p artifacts/$abi
            cp build/$abi/*.so artifacts/$abi/ || true
          done

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AndKittyInjector
          path: artifacts
