name: Build Native Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Update submodules to latest commit in main
      run: |
        git submodule update --remote --merge

    - name: Install build-essential & cmake
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Configure project with CMake
      working-directory: ./AndKittyInjector
      run: cmake -B build

    - name: Build project with CMake
      working-directory: ./AndKittyInjector
      run: cmake --build build
